services:
  - docker

before_install:
  - docker network create test
  - docker build -t samcn26/server-test -f ./server/Dockerfile.dev ./server
  - docker build -t samcn26/client-test -f ./client/Dockerfile.dev ./client
  - docker run --name mongo -d --network test -p 27017:27017 mongo
  - docker ps -a

script:
  - docker run -e MONGODB_URI=mongodb://mongo:27017/ --network test samcn26/server-test npm run test
  - docker run samcn26/client-test npm run test

after_success:
  - docker build -t samcn26/ks-client ./client
  - docker build -t samcn26/ks-server ./server
  - sh ./script/ks-mongo-build.sh
  # push to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push samcn26/ks-client
  - docker push samcn26/ks-server
  - docker push samcn26/ks-mongo

# deploy:
